# fly.toml app configuration file generated for code-challenging-bot on 2026-02-14T23:53:12Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'code-challenging-bot'
primary_region = 'gru'

[build]
  [build.args]
    GO_VERSION = '1.25.7'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "5s"
  interval = "30s"
  method = "GET"
  path = "/health"
  timeout = "5s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
